import test from 'ava';

const polishSpellingGenerator = require('../src/converters/converter-pl');

test('it generates correct string for given number', t => {
	const cases = [
		//custom
		[111, 'sto jedenaście'],
		[1001, 'jeden tysiąc jeden'],
		[1001000, 'jeden milion jeden tysiąc'],
		[1001001, 'jeden milion jeden tysiąc jeden'],
		[1000000, 'jeden milion'],
		[1000001, 'jeden milion jeden'],
		[1010111, 'jeden milion dziesięć tysięcy sto jedenaście'],
		[1000000000, 'jeden miliard'],
		[1000000000000, 'jeden bilion'],
		[1000000000111, 'jeden bilion sto jedenaście'],

		// generated
		[1, 'jeden'],
		[2, 'dwa'],
		[3, 'trzy'],
		[4, 'cztery'],
		[5, 'pięć'],
		[6, 'sześć'],
		[7, 'siedem'],
		[8, 'osiem'],
		[9, 'dziewięć'],
		[10, 'dziesięć'],
		[11, 'jedenaście'],
		[12, 'dwanaście'],
		[13, 'trzynaście'],
		[14, 'czternaście'],
		[15, 'piętnaście'],
		[16, 'szesnaście'],
		[17, 'siedemnaście'],
		[18, 'osiemnaście'],
		[19, 'dziewiętnaście'],
		[20, 'dwadzieścia'],
		[21, 'dwadzieścia jeden'],
		[22, 'dwadzieścia dwa'],
		[23, 'dwadzieścia trzy'],
		[24, 'dwadzieścia cztery'],
		[25, 'dwadzieścia pięć'],
		[26, 'dwadzieścia sześć'],
		[28, 'dwadzieścia osiem'],
		[29, 'dwadzieścia dziewięć'],
		[30, 'trzydzieści'],
		[31, 'trzydzieści jeden'],
		[32, 'trzydzieści dwa'],
		[33, 'trzydzieści trzy'],
		[34, 'trzydzieści cztery'],
		[35, 'trzydzieści pięć'],
		[36, 'trzydzieści sześć'],
		[38, 'trzydzieści osiem'],
		[39, 'trzydzieści dziewięć'],
		[40, 'czterdzieści'],
		[41, 'czterdzieści jeden'],
		[42, 'czterdzieści dwa'],
		[43, 'czterdzieści trzy'],
		[44, 'czterdzieści cztery'],
		[45, 'czterdzieści pięć'],
		[46, 'czterdzieści sześć'],
		[47, 'czterdzieści siedem'],
		[48, 'czterdzieści osiem'],
		[50, 'pięćdziesiąt'],
		[52, 'pięćdziesiąt dwa'],
		[53, 'pięćdziesiąt trzy'],
		[56, 'pięćdziesiąt sześć'],
		[57, 'pięćdziesiąt siedem'],
		[59, 'pięćdziesiąt dziewięć'],
		[60, 'sześćdziesiąt'],
		[61, 'sześćdziesiąt jeden'],
		[65, 'sześćdziesiąt pięć'],
		[66, 'sześćdziesiąt sześć'],
		[70, 'siedemdziesiąt'],
		[71, 'siedemdziesiąt jeden'],
		[73, 'siedemdziesiąt trzy'],
		[74, 'siedemdziesiąt cztery'],
		[75, 'siedemdziesiąt pięć'],
		[76, 'siedemdziesiąt sześć'],
		[77, 'siedemdziesiąt siedem'],
		[78, 'siedemdziesiąt osiem'],
		[79, 'siedemdziesiąt dziewięć'],
		[80, 'osiemdziesiąt'],
		[82, 'osiemdziesiąt dwa'],
		[83, 'osiemdziesiąt trzy'],
		[85, 'osiemdziesiąt pięć'],
		[86, 'osiemdziesiąt sześć'],
		[92, 'dziewięćdziesiąt dwa'],
		[94, 'dziewięćdziesiąt cztery'],
		[97, 'dziewięćdziesiąt siedem'],
		[98, 'dziewięćdziesiąt osiem'],
		[100, 'sto'],
		[101, 'sto jeden'],
		[107, 'sto siedem'],
		[109, 'sto dziewięć'],
		[110, 'sto dziesięć'],
		[114, 'sto czternaście'],
		[117, 'sto siedemnaście'],
		[122, 'sto dwadzieścia dwa'],
		[125, 'sto dwadzieścia pięć'],
		[127, 'sto dwadzieścia siedem'],
		[129, 'sto dwadzieścia dziewięć'],
		[130, 'sto trzydzieści'],
		[131, 'sto trzydzieści jeden'],
		[132, 'sto trzydzieści dwa'],
		[134, 'sto trzydzieści cztery'],
		[135, 'sto trzydzieści pięć'],
		[142, 'sto czterdzieści dwa'],
		[144, 'sto czterdzieści cztery'],
		[153, 'sto pięćdziesiąt trzy'],
		[154, 'sto pięćdziesiąt cztery'],
		[155, 'sto pięćdziesiąt pięć'],
		[156, 'sto pięćdziesiąt sześć'],
		[159, 'sto pięćdziesiąt dziewięć'],
		[172, 'sto siedemdziesiąt dwa'],
		[174, 'sto siedemdziesiąt cztery'],
		[177, 'sto siedemdziesiąt siedem'],
		[182, 'sto osiemdziesiąt dwa'],
		[186, 'sto osiemdziesiąt sześć'],
		[187, 'sto osiemdziesiąt siedem'],
		[198, 'sto dziewięćdziesiąt osiem'],
		[200, 'dwieście'],
		[206, 'dwieście sześć'],
		[208, 'dwieście osiem'],
		[209, 'dwieście dziewięć'],
		[210, 'dwieście dziesięć'],
		[213, 'dwieście trzynaście'],
		[217, 'dwieście siedemnaście'],
		[218, 'dwieście osiemnaście'],
		[220, 'dwieście dwadzieścia'],
		[230, 'dwieście trzydzieści'],
		[231, 'dwieście trzydzieści jeden'],
		[232, 'dwieście trzydzieści dwa'],
		[233, 'dwieście trzydzieści trzy'],
		[239, 'dwieście trzydzieści dziewięć'],
		[242, 'dwieście czterdzieści dwa'],
		[243, 'dwieście czterdzieści trzy'],
		[244, 'dwieście czterdzieści cztery'],
		[249, 'dwieście czterdzieści dziewięć'],
		[255, 'dwieście pięćdziesiąt pięć'],
		[261, 'dwieście sześćdziesiąt jeden'],
		[263, 'dwieście sześćdziesiąt trzy'],
		[264, 'dwieście sześćdziesiąt cztery'],
		[268, 'dwieście sześćdziesiąt osiem'],
		[273, 'dwieście siedemdziesiąt trzy'],
		[276, 'dwieście siedemdziesiąt sześć'],
		[285, 'dwieście osiemdziesiąt pięć'],
		[312, 'trzysta dwanaście'],
		[322, 'trzysta dwadzieścia dwa'],
		[333, 'trzysta trzydzieści trzy'],
		[335, 'trzysta trzydzieści pięć'],
		[340, 'trzysta czterdzieści'],
		[342, 'trzysta czterdzieści dwa'],
		[350, 'trzysta pięćdziesiąt'],
		[358, 'trzysta pięćdziesiąt osiem'],
		[360, 'trzysta sześćdziesiąt'],
		[362, 'trzysta sześćdziesiąt dwa'],
		[363, 'trzysta sześćdziesiąt trzy'],
		[366, 'trzysta sześćdziesiąt sześć'],
		[370, 'trzysta siedemdziesiąt'],
		[372, 'trzysta siedemdziesiąt dwa'],
		[373, 'trzysta siedemdziesiąt trzy'],
		[374, 'trzysta siedemdziesiąt cztery'],
		[389, 'trzysta osiemdziesiąt dziewięć'],
		[393, 'trzysta dziewięćdziesiąt trzy'],
		[395, 'trzysta dziewięćdziesiąt pięć'],
		[399, 'trzysta dziewięćdziesiąt dziewięć'],
		[413, 'czterysta trzynaście'],
		[420, 'czterysta dwadzieścia'],
		[422, 'czterysta dwadzieścia dwa'],
		[431, 'czterysta trzydzieści jeden'],
		[432, 'czterysta trzydzieści dwa'],
		[434, 'czterysta trzydzieści cztery'],
		[441, 'czterysta czterdzieści jeden'],
		[443, 'czterysta czterdzieści trzy'],
		[448, 'czterysta czterdzieści osiem'],
		[454, 'czterysta pięćdziesiąt cztery'],
		[455, 'czterysta pięćdziesiąt pięć'],
		[460, 'czterysta sześćdziesiąt'],
		[461, 'czterysta sześćdziesiąt jeden'],
		[464, 'czterysta sześćdziesiąt cztery'],
		[467, 'czterysta sześćdziesiąt siedem'],
		[469, 'czterysta sześćdziesiąt dziewięć'],
		[484, 'czterysta osiemdziesiąt cztery'],
		[492, 'czterysta dziewięćdziesiąt dwa'],
		[505, 'pięćset pięć'],
		[519, 'pięćset dziewiętnaście'],
		[536, 'pięćset trzydzieści sześć'],
		[539, 'pięćset trzydzieści dziewięć'],
		[555, 'pięćset pięćdziesiąt pięć'],
		[556, 'pięćset pięćdziesiąt sześć'],
		[564, 'pięćset sześćdziesiąt cztery'],
		[568, 'pięćset sześćdziesiąt osiem'],
		[570, 'pięćset siedemdziesiąt'],
		[588, 'pięćset osiemdziesiąt osiem'],
		[616, 'sześćset szesnaście'],
		[621, 'sześćset dwadzieścia jeden'],
		[632, 'sześćset trzydzieści dwa'],
		[642, 'sześćset czterdzieści dwa'],
		[644, 'sześćset czterdzieści cztery'],
		[649, 'sześćset czterdzieści dziewięć'],
		[659, 'sześćset pięćdziesiąt dziewięć'],
		[664, 'sześćset sześćdziesiąt cztery'],
		[688, 'sześćset osiemdziesiąt osiem'],
		[698, 'sześćset dziewięćdziesiąt osiem'],
		[713, 'siedemset trzynaście'],
		[721, 'siedemset dwadzieścia jeden'],
		[740, 'siedemset czterdzieści'],
		[746, 'siedemset czterdzieści sześć'],
		[763, 'siedemset sześćdziesiąt trzy'],
		[769, 'siedemset sześćdziesiąt dziewięć'],
		[772, 'siedemset siedemdziesiąt dwa'],
		[778, 'siedemset siedemdziesiąt osiem'],
		[780, 'siedemset osiemdziesiąt'],
		[845, 'osiemset czterdzieści pięć'],
		[861, 'osiemset sześćdziesiąt jeden'],
		[864, 'osiemset sześćdziesiąt cztery'],
		[869, 'osiemset sześćdziesiąt dziewięć'],
		[899, 'osiemset dziewięćdziesiąt dziewięć'],
		[910, 'dziewięćset dziesięć'],
		[954, 'dziewięćset pięćdziesiąt cztery'],
		[981, 'dziewięćset osiemdziesiąt jeden'],
		[1003, 'jeden tysiąc trzy'],
		[1011, 'jeden tysiąc jedenaście'],
		[1023, 'jeden tysiąc dwadzieścia trzy'],
		[1030, 'jeden tysiąc trzydzieści'],
		[1045, 'jeden tysiąc czterdzieści pięć'],
		[1047, 'jeden tysiąc czterdzieści siedem'],
		[1051, 'jeden tysiąc pięćdziesiąt jeden'],
		[1058, 'jeden tysiąc pięćdziesiąt osiem'],
		[1062, 'jeden tysiąc sześćdziesiąt dwa'],
		[1068, 'jeden tysiąc sześćdziesiąt osiem'],
		[1076, 'jeden tysiąc siedemdziesiąt sześć'],
		[1077, 'jeden tysiąc siedemdziesiąt siedem'],
		[1082, 'jeden tysiąc osiemdziesiąt dwa'],
		[1096, 'jeden tysiąc dziewięćdziesiąt sześć'],
		[1107, 'jeden tysiąc sto siedem'],
		[1114, 'jeden tysiąc sto czternaście'],
		[1120, 'jeden tysiąc sto dwadzieścia'],
		[1138, 'jeden tysiąc sto trzydzieści osiem'],
		[1140, 'jeden tysiąc sto czterdzieści'],
		[1175, 'jeden tysiąc sto siedemdziesiąt pięć'],
		[1198, 'jeden tysiąc sto dziewięćdziesiąt osiem'],
		[1202, 'jeden tysiąc dwieście dwa'],
		[1228, 'jeden tysiąc dwieście dwadzieścia osiem'],
		[1245, 'jeden tysiąc dwieście czterdzieści pięć'],
		[1256, 'jeden tysiąc dwieście pięćdziesiąt sześć'],
		[1258, 'jeden tysiąc dwieście pięćdziesiąt osiem'],
		[1262, 'jeden tysiąc dwieście sześćdziesiąt dwa'],
		[1265, 'jeden tysiąc dwieście sześćdziesiąt pięć'],
		[1269, 'jeden tysiąc dwieście sześćdziesiąt dziewięć'],
		[1277, 'jeden tysiąc dwieście siedemdziesiąt siedem'],
		[1300, 'jeden tysiąc trzysta'],
		[1306, 'jeden tysiąc trzysta sześć'],
		[1310, 'jeden tysiąc trzysta dziesięć'],
		[1338, 'jeden tysiąc trzysta trzydzieści osiem'],
		[1348, 'jeden tysiąc trzysta czterdzieści osiem'],
		[1353, 'jeden tysiąc trzysta pięćdziesiąt trzy'],
		[1374, 'jeden tysiąc trzysta siedemdziesiąt cztery'],
		[1381, 'jeden tysiąc trzysta osiemdziesiąt jeden'],
		[1409, 'jeden tysiąc czterysta dziewięć'],
		[1427, 'jeden tysiąc czterysta dwadzieścia siedem'],
		[1441, 'jeden tysiąc czterysta czterdzieści jeden'],
		[1478, 'jeden tysiąc czterysta siedemdziesiąt osiem'],
		[1506, 'jeden tysiąc pięćset sześć'],
		[1508, 'jeden tysiąc pięćset osiem'],
		[1515, 'jeden tysiąc pięćset piętnaście'],
		[1532, 'jeden tysiąc pięćset trzydzieści dwa'],
		[1561, 'jeden tysiąc pięćset sześćdziesiąt jeden'],
		[1571, 'jeden tysiąc pięćset siedemdziesiąt jeden'],
		[1608, 'jeden tysiąc sześćset osiem'],
		[1636, 'jeden tysiąc sześćset trzydzieści sześć'],
		[1662, 'jeden tysiąc sześćset sześćdziesiąt dwa'],
		[1665, 'jeden tysiąc sześćset sześćdziesiąt pięć'],
		[1728, 'jeden tysiąc siedemset dwadzieścia osiem'],
		[1732, 'jeden tysiąc siedemset trzydzieści dwa'],
		[1794, 'jeden tysiąc siedemset dziewięćdziesiąt cztery'],
		[1800, 'jeden tysiąc osiemset'],
		[1813, 'jeden tysiąc osiemset trzynaście'],
		[1828, 'jeden tysiąc osiemset dwadzieścia osiem'],
		[1898, 'jeden tysiąc osiemset dziewięćdziesiąt osiem'],
		[1909, 'jeden tysiąc dziewięćset dziewięć'],
		[1934, 'jeden tysiąc dziewięćset trzydzieści cztery'],
		[1945, 'jeden tysiąc dziewięćset czterdzieści pięć'],
		[1946, 'jeden tysiąc dziewięćset czterdzieści sześć'],
		[1962, 'jeden tysiąc dziewięćset sześćdziesiąt dwa'],
		[1983, 'jeden tysiąc dziewięćset osiemdziesiąt trzy'],
		[1993, 'jeden tysiąc dziewięćset dziewięćdziesiąt trzy'],
		[1998, 'jeden tysiąc dziewięćset dziewięćdziesiąt osiem'],
		[2078, 'dwa tysiące siedemdziesiąt osiem'],
		[2125, 'dwa tysiące sto dwadzieścia pięć'],
		[2138, 'dwa tysiące sto trzydzieści osiem'],
		[2206, 'dwa tysiące dwieście sześć'],
		[2292, 'dwa tysiące dwieście dziewięćdziesiąt dwa'],
		[2330, 'dwa tysiące trzysta trzydzieści'],
		[2372, 'dwa tysiące trzysta siedemdziesiąt dwa'],
		[2414, 'dwa tysiące czterysta czternaście'],
		[2607, 'dwa tysiące sześćset siedem'],
		[2648, 'dwa tysiące sześćset czterdzieści osiem'],
		[2649, 'dwa tysiące sześćset czterdzieści dziewięć'],
		[2674, 'dwa tysiące sześćset siedemdziesiąt cztery'],
		[2690, 'dwa tysiące sześćset dziewięćdziesiąt'],
		[2727, 'dwa tysiące siedemset dwadzieścia siedem'],
		[2809, 'dwa tysiące osiemset dziewięć'],
		[2822, 'dwa tysiące osiemset dwadzieścia dwa'],
		[2862, 'dwa tysiące osiemset sześćdziesiąt dwa'],
		[2999, 'dwa tysiące dziewięćset dziewięćdziesiąt dziewięć'],
		[3055, 'trzy tysiące pięćdziesiąt pięć'],
		[3098, 'trzy tysiące dziewięćdziesiąt osiem'],
		[3153, 'trzy tysiące sto pięćdziesiąt trzy'],
		[3155, 'trzy tysiące sto pięćdziesiąt pięć'],
		[3187, 'trzy tysiące sto osiemdziesiąt siedem'],
		[3289, 'trzy tysiące dwieście osiemdziesiąt dziewięć'],
		[3303, 'trzy tysiące trzysta trzy'],
		[3304, 'trzy tysiące trzysta cztery'],
		[3468, 'trzy tysiące czterysta sześćdziesiąt osiem'],
		[3489, 'trzy tysiące czterysta osiemdziesiąt dziewięć'],
		[3601, 'trzy tysiące sześćset jeden'],
		[3609, 'trzy tysiące sześćset dziewięć'],
		[3718, 'trzy tysiące siedemset osiemnaście'],
		[3776, 'trzy tysiące siedemset siedemdziesiąt sześć'],
		[3789, 'trzy tysiące siedemset osiemdziesiąt dziewięć'],
		[3827, 'trzy tysiące osiemset dwadzieścia siedem'],
		[3847, 'trzy tysiące osiemset czterdzieści siedem'],
		[3939, 'trzy tysiące dziewięćset trzydzieści dziewięć'],
		[3954, 'trzy tysiące dziewięćset pięćdziesiąt cztery'],
		[4016, 'cztery tysiące szesnaście'],
		[4071, 'cztery tysiące siedemdziesiąt jeden'],
		[4397, 'cztery tysiące trzysta dziewięćdziesiąt siedem'],
		[4406, 'cztery tysiące czterysta sześć'],
		[4577, 'cztery tysiące pięćset siedemdziesiąt siedem'],
		[4602, 'cztery tysiące sześćset dwa'],
		[4609, 'cztery tysiące sześćset dziewięć'],
		[4625, 'cztery tysiące sześćset dwadzieścia pięć'],
		[4692, 'cztery tysiące sześćset dziewięćdziesiąt dwa'],
		[4768, 'cztery tysiące siedemset sześćdziesiąt osiem'],
		[4781, 'cztery tysiące siedemset osiemdziesiąt jeden'],
		[4916, 'cztery tysiące dziewięćset szesnaście'],
		[4975, 'cztery tysiące dziewięćset siedemdziesiąt pięć'],
		[5145, 'pięć tysięcy sto czterdzieści pięć'],
		[5198, 'pięć tysięcy sto dziewięćdziesiąt osiem'],
		[5218, 'pięć tysięcy dwieście osiemnaście'],
		[5225, 'pięć tysięcy dwieście dwadzieścia pięć'],
		[5251, 'pięć tysięcy dwieście pięćdziesiąt jeden'],
		[5270, 'pięć tysięcy dwieście siedemdziesiąt'],
		[5311, 'pięć tysięcy trzysta jedenaście'],
		[5404, 'pięć tysięcy czterysta cztery'],
		[5454, 'pięć tysięcy czterysta pięćdziesiąt cztery'],
		[5463, 'pięć tysięcy czterysta sześćdziesiąt trzy'],
		[5468, 'pięć tysięcy czterysta sześćdziesiąt osiem'],
		[5524, 'pięć tysięcy pięćset dwadzieścia cztery'],
		[5750, 'pięć tysięcy siedemset pięćdziesiąt'],
		[5758, 'pięć tysięcy siedemset pięćdziesiąt osiem'],
		[5788, 'pięć tysięcy siedemset osiemdziesiąt osiem'],
		[5897, 'pięć tysięcy osiemset dziewięćdziesiąt siedem'],
		[6062, 'sześć tysięcy sześćdziesiąt dwa'],
		[6066, 'sześć tysięcy sześćdziesiąt sześć'],
		[6122, 'sześć tysięcy sto dwadzieścia dwa'],
		[6166, 'sześć tysięcy sto sześćdziesiąt sześć'],
		[6361, 'sześć tysięcy trzysta sześćdziesiąt jeden'],
		[6373, 'sześć tysięcy trzysta siedemdziesiąt trzy'],
		[6441, 'sześć tysięcy czterysta czterdzieści jeden'],
		[6459, 'sześć tysięcy czterysta pięćdziesiąt dziewięć'],
		[6478, 'sześć tysięcy czterysta siedemdziesiąt osiem'],
		[6509, 'sześć tysięcy pięćset dziewięć'],
		[6557, 'sześć tysięcy pięćset pięćdziesiąt siedem'],
		[6675, 'sześć tysięcy sześćset siedemdziesiąt pięć'],
		[6864, 'sześć tysięcy osiemset sześćdziesiąt cztery'],
		[7009, 'siedem tysięcy dziewięć'],
		[7032, 'siedem tysięcy trzydzieści dwa'],
		[7125, 'siedem tysięcy sto dwadzieścia pięć'],
		[7173, 'siedem tysięcy sto siedemdziesiąt trzy'],
		[7298, 'siedem tysięcy dwieście dziewięćdziesiąt osiem'],
		[7411, 'siedem tysięcy czterysta jedenaście'],
		[7580, 'siedem tysięcy pięćset osiemdziesiąt'],
		[7800, 'siedem tysięcy osiemset'],
		[7823, 'siedem tysięcy osiemset dwadzieścia trzy'],
		[7881, 'siedem tysięcy osiemset osiemdziesiąt jeden'],
		[7890, 'siedem tysięcy osiemset dziewięćdziesiąt'],
		[7954, 'siedem tysięcy dziewięćset pięćdziesiąt cztery'],
		[8136, 'osiem tysięcy sto trzydzieści sześć'],
		[8205, 'osiem tysięcy dwieście pięć'],
		[8262, 'osiem tysięcy dwieście sześćdziesiąt dwa'],
		[8344, 'osiem tysięcy trzysta czterdzieści cztery'],
		[8442, 'osiem tysięcy czterysta czterdzieści dwa'],
		[8472, 'osiem tysięcy czterysta siedemdziesiąt dwa'],
		[8504, 'osiem tysięcy pięćset cztery'],
		[8506, 'osiem tysięcy pięćset sześć'],
		[8698, 'osiem tysięcy sześćset dziewięćdziesiąt osiem'],
		[8713, 'osiem tysięcy siedemset trzynaście'],
		[8839, 'osiem tysięcy osiemset trzydzieści dziewięć'],
		[8897, 'osiem tysięcy osiemset dziewięćdziesiąt siedem'],
		[9319, 'dziewięć tysięcy trzysta dziewiętnaście'],
		[9488, 'dziewięć tysięcy czterysta osiemdziesiąt osiem'],
		[9629, 'dziewięć tysięcy sześćset dwadzieścia dziewięć'],
		[9673, 'dziewięć tysięcy sześćset siedemdziesiąt trzy'],
		[10266, 'dziesięć tysięcy dwieście sześćdziesiąt sześć'],
		[10594, 'dziesięć tysięcy pięćset dziewięćdziesiąt cztery'],
		[11162, 'jedenaście tysięcy sto sześćdziesiąt dwa'],
		[11271, 'jedenaście tysięcy dwieście siedemdziesiąt jeden'],
		[11379, 'jedenaście tysięcy trzysta siedemdziesiąt dziewięć'],
		[11473, 'jedenaście tysięcy czterysta siedemdziesiąt trzy'],
		[11626, 'jedenaście tysięcy sześćset dwadzieścia sześć'],
		[11641, 'jedenaście tysięcy sześćset czterdzieści jeden'],
		[11696, 'jedenaście tysięcy sześćset dziewięćdziesiąt sześć'],
		[11739, 'jedenaście tysięcy siedemset trzydzieści dziewięć'],
		[11809, 'jedenaście tysięcy osiemset dziewięć'],
		[11871, 'jedenaście tysięcy osiemset siedemdziesiąt jeden'],
		[11938, 'jedenaście tysięcy dziewięćset trzydzieści osiem'],
		[12184, 'dwanaście tysięcy sto osiemdziesiąt cztery'],
		[12442, 'dwanaście tysięcy czterysta czterdzieści dwa'],
		[12471, 'dwanaście tysięcy czterysta siedemdziesiąt jeden'],
		[12572, 'dwanaście tysięcy pięćset siedemdziesiąt dwa'],
		[12885, 'dwanaście tysięcy osiemset osiemdziesiąt pięć'],
		[13117, 'trzynaście tysięcy sto siedemnaście'],
		[13301, 'trzynaście tysięcy trzysta jeden'],
		[13313, 'trzynaście tysięcy trzysta trzynaście'],
		[13481, 'trzynaście tysięcy czterysta osiemdziesiąt jeden'],
		[13728, 'trzynaście tysięcy siedemset dwadzieścia osiem'],
		[14368, 'czternaście tysięcy trzysta sześćdziesiąt osiem'],
		[14751, 'czternaście tysięcy siedemset pięćdziesiąt jeden'],
		[14902, 'czternaście tysięcy dziewięćset dwa'],
		[15043, 'piętnaście tysięcy czterdzieści trzy'],
		[15195, 'piętnaście tysięcy sto dziewięćdziesiąt pięć'],
		[15247, 'piętnaście tysięcy dwieście czterdzieści siedem'],
		[15387, 'piętnaście tysięcy trzysta osiemdziesiąt siedem'],
		[15518, 'piętnaście tysięcy pięćset osiemnaście'],
		[15565, 'piętnaście tysięcy pięćset sześćdziesiąt pięć'],
		[16265, 'szesnaście tysięcy dwieście sześćdziesiąt pięć'],
		[16948, 'szesnaście tysięcy dziewięćset czterdzieści osiem'],
		[17468, 'siedemnaście tysięcy czterysta sześćdziesiąt osiem'],
		[18032, 'osiemnaście tysięcy trzydzieści dwa'],
		[18333, 'osiemnaście tysięcy trzysta trzydzieści trzy'],
		[18349, 'osiemnaście tysięcy trzysta czterdzieści dziewięć'],
		[18352, 'osiemnaście tysięcy trzysta pięćdziesiąt dwa'],
		[18747, 'osiemnaście tysięcy siedemset czterdzieści siedem'],
		[18935, 'osiemnaście tysięcy dziewięćset trzydzieści pięć'],
		[19204, 'dziewiętnaście tysięcy dwieście cztery'],
		[19391, 'dziewiętnaście tysięcy trzysta dziewięćdziesiąt jeden'],
		[19673, 'dziewiętnaście tysięcy sześćset siedemdziesiąt trzy'],
		[19676, 'dziewiętnaście tysięcy sześćset siedemdziesiąt sześć'],
		[19941, 'dziewiętnaście tysięcy dziewięćset czterdzieści jeden'],
		[20559, 'dwadzieścia tysięcy pięćset pięćdziesiąt dziewięć'],
		[21073, 'dwadzieścia jeden tysięcy siedemdziesiąt trzy'],
		[21211, 'dwadzieścia jeden tysięcy dwieście jedenaście'],
		[21287, 'dwadzieścia jeden tysięcy dwieście osiemdziesiąt siedem'],
		[21317, 'dwadzieścia jeden tysięcy trzysta siedemnaście'],
		[21548, 'dwadzieścia jeden tysięcy pięćset czterdzieści osiem'],
		[22065, 'dwadzieścia dwa tysiące sześćdziesiąt pięć'],
		[22157, 'dwadzieścia dwa tysiące sto pięćdziesiąt siedem'],
		[22412, 'dwadzieścia dwa tysiące czterysta dwanaście'],
		[22905, 'dwadzieścia dwa tysiące dziewięćset pięć'],
		[23020, 'dwadzieścia trzy tysiące dwadzieścia'],
		[23037, 'dwadzieścia trzy tysiące trzydzieści siedem'],
		[23192, 'dwadzieścia trzy tysiące sto dziewięćdziesiąt dwa'],
		[23455, 'dwadzieścia trzy tysiące czterysta pięćdziesiąt pięć'],
		[23476, 'dwadzieścia trzy tysiące czterysta siedemdziesiąt sześć'],
		[23569, 'dwadzieścia trzy tysiące pięćset sześćdziesiąt dziewięć'],
		[23951, 'dwadzieścia trzy tysiące dziewięćset pięćdziesiąt jeden'],
		[24031, 'dwadzieścia cztery tysiące trzydzieści jeden'],
		[24577, 'dwadzieścia cztery tysiące pięćset siedemdziesiąt siedem'],
		[25143, 'dwadzieścia pięć tysięcy sto czterdzieści trzy'],
		[25386, 'dwadzieścia pięć tysięcy trzysta osiemdziesiąt sześć'],
		[25448, 'dwadzieścia pięć tysięcy czterysta czterdzieści osiem'],
		[26639, 'dwadzieścia sześć tysięcy sześćset trzydzieści dziewięć'],
		[26684, 'dwadzieścia sześć tysięcy sześćset osiemdziesiąt cztery'],
		[26733, 'dwadzieścia sześć tysięcy siedemset trzydzieści trzy'],
		[27035, 'dwadzieścia siedem tysięcy trzydzieści pięć'],
		[27185, 'dwadzieścia siedem tysięcy sto osiemdziesiąt pięć'],
		[27760, 'dwadzieścia siedem tysięcy siedemset sześćdziesiąt'],
		[27827, 'dwadzieścia siedem tysięcy osiemset dwadzieścia siedem'],
		[28840, 'dwadzieścia osiem tysięcy osiemset czterdzieści'],
		[28895, 'dwadzieścia osiem tysięcy osiemset dziewięćdziesiąt pięć'],
		[28979, 'dwadzieścia osiem tysięcy dziewięćset siedemdziesiąt dziewięć'],
		[29823, 'dwadzieścia dziewięć tysięcy osiemset dwadzieścia trzy'],
		[30261, 'trzydzieści tysięcy dwieście sześćdziesiąt jeden'],
		[30569, 'trzydzieści tysięcy pięćset sześćdziesiąt dziewięć'],
		[30653, 'trzydzieści tysięcy sześćset pięćdziesiąt trzy'],
		[30924, 'trzydzieści tysięcy dziewięćset dwadzieścia cztery'],
		[31176, 'trzydzieści jeden tysięcy sto siedemdziesiąt sześć'],
		[31650, 'trzydzieści jeden tysięcy sześćset pięćdziesiąt'],
		[32869, 'trzydzieści dwa tysiące osiemset sześćdziesiąt dziewięć'],
		[33133, 'trzydzieści trzy tysiące sto trzydzieści trzy'],
		[33515, 'trzydzieści trzy tysiące pięćset piętnaście'],
		[33650, 'trzydzieści trzy tysiące sześćset pięćdziesiąt'],
		[34045, 'trzydzieści cztery tysiące czterdzieści pięć'],
		[34294, 'trzydzieści cztery tysiące dwieście dziewięćdziesiąt cztery'],
		[34938, 'trzydzieści cztery tysiące dziewięćset trzydzieści osiem'],
		[35777, 'trzydzieści pięć tysięcy siedemset siedemdziesiąt siedem'],
		[36277, 'trzydzieści sześć tysięcy dwieście siedemdziesiąt siedem'],
		[36765, 'trzydzieści sześć tysięcy siedemset sześćdziesiąt pięć'],
		[37502, 'trzydzieści siedem tysięcy pięćset dwa'],
		[37640, 'trzydzieści siedem tysięcy sześćset czterdzieści'],
		[38226, 'trzydzieści osiem tysięcy dwieście dwadzieścia sześć'],
		[38898, 'trzydzieści osiem tysięcy osiemset dziewięćdziesiąt osiem'],
		[39157, 'trzydzieści dziewięć tysięcy sto pięćdziesiąt siedem'],
		[39378, 'trzydzieści dziewięć tysięcy trzysta siedemdziesiąt osiem'],
		[39474, 'trzydzieści dziewięć tysięcy czterysta siedemdziesiąt cztery'],
		[39603, 'trzydzieści dziewięć tysięcy sześćset trzy'],
		[39956, 'trzydzieści dziewięć tysięcy dziewięćset pięćdziesiąt sześć'],
		[40880, 'czterdzieści tysięcy osiemset osiemdziesiąt'],
		[41272, 'czterdzieści jeden tysięcy dwieście siedemdziesiąt dwa'],
		[42039, 'czterdzieści dwa tysiące trzydzieści dziewięć'],
		[42609, 'czterdzieści dwa tysiące sześćset dziewięć'],
		[42961, 'czterdzieści dwa tysiące dziewięćset sześćdziesiąt jeden'],
		[43653, 'czterdzieści trzy tysiące sześćset pięćdziesiąt trzy'],
		[44112, 'czterdzieści cztery tysiące sto dwanaście'],
		[44273, 'czterdzieści cztery tysiące dwieście siedemdziesiąt trzy'],
		[44617, 'czterdzieści cztery tysiące sześćset siedemnaście'],
		[44695, 'czterdzieści cztery tysiące sześćset dziewięćdziesiąt pięć'],
		[44809, 'czterdzieści cztery tysiące osiemset dziewięć'],
		[45562, 'czterdzieści pięć tysięcy pięćset sześćdziesiąt dwa'],
		[46478, 'czterdzieści sześć tysięcy czterysta siedemdziesiąt osiem'],
		[47241, 'czterdzieści siedem tysięcy dwieście czterdzieści jeden'],
		[48556, 'czterdzieści osiem tysięcy pięćset pięćdziesiąt sześć'],
		[48996, 'czterdzieści osiem tysięcy dziewięćset dziewięćdziesiąt sześć'],
		[49758, 'czterdzieści dziewięć tysięcy siedemset pięćdziesiąt osiem'],
		[50190, 'pięćdziesiąt tysięcy sto dziewięćdziesiąt'],
		[52351, 'pięćdziesiąt dwa tysiące trzysta pięćdziesiąt jeden'],
		[53385, 'pięćdziesiąt trzy tysiące trzysta osiemdziesiąt pięć'],
		[53913, 'pięćdziesiąt trzy tysiące dziewięćset trzynaście'],
		[53992, 'pięćdziesiąt trzy tysiące dziewięćset dziewięćdziesiąt dwa'],
		[54892, 'pięćdziesiąt cztery tysiące osiemset dziewięćdziesiąt dwa'],
		[56570, 'pięćdziesiąt sześć tysięcy pięćset siedemdziesiąt'],
		[57800, 'pięćdziesiąt siedem tysięcy osiemset'],
		[58518, 'pięćdziesiąt osiem tysięcy pięćset osiemnaście'],
		[60462, 'sześćdziesiąt tysięcy czterysta sześćdziesiąt dwa'],
		[62964, 'sześćdziesiąt dwa tysiące dziewięćset sześćdziesiąt cztery'],
		[63665, 'sześćdziesiąt trzy tysiące sześćset sześćdziesiąt pięć'],
		[63906, 'sześćdziesiąt trzy tysiące dziewięćset sześć'],
		[64603, 'sześćdziesiąt cztery tysiące sześćset trzy'],
		[67382, 'sześćdziesiąt siedem tysięcy trzysta osiemdziesiąt dwa'],
		[67959, 'sześćdziesiąt siedem tysięcy dziewięćset pięćdziesiąt dziewięć'],
		[69485, 'sześćdziesiąt dziewięć tysięcy czterysta osiemdziesiąt pięć'],
		[69969, 'sześćdziesiąt dziewięć tysięcy dziewięćset sześćdziesiąt dziewięć'],
		[71886, 'siedemdziesiąt jeden tysięcy osiemset osiemdziesiąt sześć'],
		[74119, 'siedemdziesiąt cztery tysiące sto dziewiętnaście'],
		[74205, 'siedemdziesiąt cztery tysiące dwieście pięć'],
		[75278, 'siedemdziesiąt pięć tysięcy dwieście siedemdziesiąt osiem'],
		[75465, 'siedemdziesiąt pięć tysięcy czterysta sześćdziesiąt pięć'],
		[76193, 'siedemdziesiąt sześć tysięcy sto dziewięćdziesiąt trzy'],
		[76230, 'siedemdziesiąt sześć tysięcy dwieście trzydzieści'],
		[76497, 'siedemdziesiąt sześć tysięcy czterysta dziewięćdziesiąt siedem'],
		[76629, 'siedemdziesiąt sześć tysięcy sześćset dwadzieścia dziewięć'],
		[79131, 'siedemdziesiąt dziewięć tysięcy sto trzydzieści jeden'],
		[79848, 'siedemdziesiąt dziewięć tysięcy osiemset czterdzieści osiem'],
		[80156, 'osiemdziesiąt tysięcy sto pięćdziesiąt sześć'],
		[80278, 'osiemdziesiąt tysięcy dwieście siedemdziesiąt osiem'],
		[82052, 'osiemdziesiąt dwa tysiące pięćdziesiąt dwa'],
		[82614, 'osiemdziesiąt dwa tysiące sześćset czternaście'],
		[85103, 'osiemdziesiąt pięć tysięcy sto trzy'],
		[85131, 'osiemdziesiąt pięć tysięcy sto trzydzieści jeden'],
		[86055, 'osiemdziesiąt sześć tysięcy pięćdziesiąt pięć'],
		[86425, 'osiemdziesiąt sześć tysięcy czterysta dwadzieścia pięć'],
		[92131, 'dziewięćdziesiąt dwa tysiące sto trzydzieści jeden'],
		[93486, 'dziewięćdziesiąt trzy tysiące czterysta osiemdziesiąt sześć'],
		[96742, 'dziewięćdziesiąt sześć tysięcy siedemset czterdzieści dwa'],
		[96756, 'dziewięćdziesiąt sześć tysięcy siedemset pięćdziesiąt sześć'],
		[97283, 'dziewięćdziesiąt siedem tysięcy dwieście osiemdziesiąt trzy'],
		[97928, 'dziewięćdziesiąt siedem tysięcy dziewięćset dwadzieścia osiem'],
		[98660, 'dziewięćdziesiąt osiem tysięcy sześćset sześćdziesiąt'],
		[99392, 'dziewięćdziesiąt dziewięć tysięcy trzysta dziewięćdziesiąt dwa'],
		[99855, 'dziewięćdziesiąt dziewięć tysięcy osiemset pięćdziesiąt pięć'],
		[100156, 'sto tysięcy sto pięćdziesiąt sześć'],
		[100919, 'sto tysięcy dziewięćset dziewiętnaście'],
		[101538, 'sto jeden tysięcy pięćset trzydzieści osiem'],
		[102192, 'sto dwa tysiące sto dziewięćdziesiąt dwa'],
		[106114, 'sto sześć tysięcy sto czternaście'],
		[107323, 'sto siedem tysięcy trzysta dwadzieścia trzy'],
		[107383, 'sto siedem tysięcy trzysta osiemdziesiąt trzy'],
		[107988, 'sto siedem tysięcy dziewięćset osiemdziesiąt osiem'],
		[113198, 'sto trzynaście tysięcy sto dziewięćdziesiąt osiem'],
		[113291, 'sto trzynaście tysięcy dwieście dziewięćdziesiąt jeden'],
		[117884, 'sto siedemnaście tysięcy osiemset osiemdziesiąt cztery'],
		[119124, 'sto dziewiętnaście tysięcy sto dwadzieścia cztery'],
		[123603, 'sto dwadzieścia trzy tysiące sześćset trzy'],
		[123769, 'sto dwadzieścia trzy tysiące siedemset sześćdziesiąt dziewięć'],
		[125848, 'sto dwadzieścia pięć tysięcy osiemset czterdzieści osiem'],
		[126218, 'sto dwadzieścia sześć tysięcy dwieście osiemnaście'],
		[128455, 'sto dwadzieścia osiem tysięcy czterysta pięćdziesiąt pięć'],
		[128470, 'sto dwadzieścia osiem tysięcy czterysta siedemdziesiąt'],
		[129207, 'sto dwadzieścia dziewięć tysięcy dwieście siedem'],
		[130539, 'sto trzydzieści tysięcy pięćset trzydzieści dziewięć'],
		[133301, 'sto trzydzieści trzy tysiące trzysta jeden'],
		[136736, 'sto trzydzieści sześć tysięcy siedemset trzydzieści sześć'],
		[139193, 'sto trzydzieści dziewięć tysięcy sto dziewięćdziesiąt trzy'],
		[140643, 'sto czterdzieści tysięcy sześćset czterdzieści trzy'],
		[145443, 'sto czterdzieści pięć tysięcy czterysta czterdzieści trzy'],
		[146519, 'sto czterdzieści sześć tysięcy pięćset dziewiętnaście'],
		[148500, 'sto czterdzieści osiem tysięcy pięćset'],
		[151650, 'sto pięćdziesiąt jeden tysięcy sześćset pięćdziesiąt'],
		[153176, 'sto pięćdziesiąt trzy tysiące sto siedemdziesiąt sześć'],
		[156630, 'sto pięćdziesiąt sześć tysięcy sześćset trzydzieści'],
		[156634, 'sto pięćdziesiąt sześć tysięcy sześćset trzydzieści cztery'],
		[159425, 'sto pięćdziesiąt dziewięć tysięcy czterysta dwadzieścia pięć'],
		[161654, 'sto sześćdziesiąt jeden tysięcy sześćset pięćdziesiąt cztery'],
		[164114, 'sto sześćdziesiąt cztery tysiące sto czternaście'],
		[166115, 'sto sześćdziesiąt sześć tysięcy sto piętnaście'],
		[168947, 'sto sześćdziesiąt osiem tysięcy dziewięćset czterdzieści siedem'],
		[172850, 'sto siedemdziesiąt dwa tysiące osiemset pięćdziesiąt'],
		[175169, 'sto siedemdziesiąt pięć tysięcy sto sześćdziesiąt dziewięć'],
		[183768, 'sto osiemdziesiąt trzy tysiące siedemset sześćdziesiąt osiem'],
		[187895, 'sto osiemdziesiąt siedem tysięcy osiemset dziewięćdziesiąt pięć'],
		[188552, 'sto osiemdziesiąt osiem tysięcy pięćset pięćdziesiąt dwa'],
		[189142, 'sto osiemdziesiąt dziewięć tysięcy sto czterdzieści dwa'],
		[191618, 'sto dziewięćdziesiąt jeden tysięcy sześćset osiemnaście'],
		[194880, 'sto dziewięćdziesiąt cztery tysiące osiemset osiemdziesiąt'],
		[196530, 'sto dziewięćdziesiąt sześć tysięcy pięćset trzydzieści'],
		[197024, 'sto dziewięćdziesiąt siedem tysięcy dwadzieścia cztery'],
		[197707, 'sto dziewięćdziesiąt siedem tysięcy siedemset siedem'],
		[199376, 'sto dziewięćdziesiąt dziewięć tysięcy trzysta siedemdziesiąt sześć'],
		[201156, 'dwieście jeden tysięcy sto pięćdziesiąt sześć'],
		[204544, 'dwieście cztery tysiące pięćset czterdzieści cztery'],
		[205178, 'dwieście pięć tysięcy sto siedemdziesiąt osiem'],
		[209477, 'dwieście dziewięć tysięcy czterysta siedemdziesiąt siedem'],
		[209711, 'dwieście dziewięć tysięcy siedemset jedenaście'],
		[211023, 'dwieście jedenaście tysięcy dwadzieścia trzy'],
		[211926, 'dwieście jedenaście tysięcy dziewięćset dwadzieścia sześć'],
		[212630, 'dwieście dwanaście tysięcy sześćset trzydzieści'],
		[223521, 'dwieście dwadzieścia trzy tysiące pięćset dwadzieścia jeden'],
		[226726, 'dwieście dwadzieścia sześć tysięcy siedemset dwadzieścia sześć'],
		[229958, 'dwieście dwadzieścia dziewięć tysięcy dziewięćset pięćdziesiąt osiem'],
		[236345, 'dwieście trzydzieści sześć tysięcy trzysta czterdzieści pięć'],
		[236772, 'dwieście trzydzieści sześć tysięcy siedemset siedemdziesiąt dwa'],
		[244479, 'dwieście czterdzieści cztery tysiące czterysta siedemdziesiąt dziewięć'],
		[245559, 'dwieście czterdzieści pięć tysięcy pięćset pięćdziesiąt dziewięć'],
		[253797, 'dwieście pięćdziesiąt trzy tysiące siedemset dziewięćdziesiąt siedem'],
		[254876, 'dwieście pięćdziesiąt cztery tysiące osiemset siedemdziesiąt sześć'],
		[256800, 'dwieście pięćdziesiąt sześć tysięcy osiemset'],
		[259555, 'dwieście pięćdziesiąt dziewięć tysięcy pięćset pięćdziesiąt pięć'],
		[259759, 'dwieście pięćdziesiąt dziewięć tysięcy siedemset pięćdziesiąt dziewięć'],
		[260702, 'dwieście sześćdziesiąt tysięcy siedemset dwa'],
		[266342, 'dwieście sześćdziesiąt sześć tysięcy trzysta czterdzieści dwa'],
		[281681, 'dwieście osiemdziesiąt jeden tysięcy sześćset osiemdziesiąt jeden'],
		[303270, 'trzysta trzy tysiące dwieście siedemdziesiąt'],
		[307207, 'trzysta siedem tysięcy dwieście siedem'],
		[309760, 'trzysta dziewięć tysięcy siedemset sześćdziesiąt'],
		[310199, 'trzysta dziesięć tysięcy sto dziewięćdziesiąt dziewięć'],
		[312303, 'trzysta dwanaście tysięcy trzysta trzy'],
		[317944, 'trzysta siedemnaście tysięcy dziewięćset czterdzieści cztery'],
		[329168, 'trzysta dwadzieścia dziewięć tysięcy sto sześćdziesiąt osiem'],
		[335093, 'trzysta trzydzieści pięć tysięcy dziewięćdziesiąt trzy'],
		[336578, 'trzysta trzydzieści sześć tysięcy pięćset siedemdziesiąt osiem'],
		[338620, 'trzysta trzydzieści osiem tysięcy sześćset dwadzieścia'],
		[338705, 'trzysta trzydzieści osiem tysięcy siedemset pięć'],
		[343290, 'trzysta czterdzieści trzy tysiące dwieście dziewięćdziesiąt'],
		[344087, 'trzysta czterdzieści cztery tysiące osiemdziesiąt siedem'],
		[347649, 'trzysta czterdzieści siedem tysięcy sześćset czterdzieści dziewięć'],
		[350606, 'trzysta pięćdziesiąt tysięcy sześćset sześć'],
		[353919, 'trzysta pięćdziesiąt trzy tysiące dziewięćset dziewiętnaście'],
		[358264, 'trzysta pięćdziesiąt osiem tysięcy dwieście sześćdziesiąt cztery'],
		[363979, 'trzysta sześćdziesiąt trzy tysiące dziewięćset siedemdziesiąt dziewięć'],
		[365965, 'trzysta sześćdziesiąt pięć tysięcy dziewięćset sześćdziesiąt pięć'],
		[368254, 'trzysta sześćdziesiąt osiem tysięcy dwieście pięćdziesiąt cztery'],
		[368962, 'trzysta sześćdziesiąt osiem tysięcy dziewięćset sześćdziesiąt dwa'],
		[372567, 'trzysta siedemdziesiąt dwa tysiące pięćset sześćdziesiąt siedem'],
		[377382, 'trzysta siedemdziesiąt siedem tysięcy trzysta osiemdziesiąt dwa'],
		[386470, 'trzysta osiemdziesiąt sześć tysięcy czterysta siedemdziesiąt'],
		[394884, 'trzysta dziewięćdziesiąt cztery tysiące osiemset osiemdziesiąt cztery'],
		[399087, 'trzysta dziewięćdziesiąt dziewięć tysięcy osiemdziesiąt siedem'],
		[404478, 'czterysta cztery tysiące czterysta siedemdziesiąt osiem'],
		[405932, 'czterysta pięć tysięcy dziewięćset trzydzieści dwa'],
		[421847, 'czterysta dwadzieścia jeden tysięcy osiemset czterdzieści siedem'],
		[423608, 'czterysta dwadzieścia trzy tysiące sześćset osiem'],
		[432803, 'czterysta trzydzieści dwa tysiące osiemset trzy'],
		[432845, 'czterysta trzydzieści dwa tysiące osiemset czterdzieści pięć'],
		[444685, 'czterysta czterdzieści cztery tysiące sześćset osiemdziesiąt pięć'],
		[445984, 'czterysta czterdzieści pięć tysięcy dziewięćset osiemdziesiąt cztery'],
		[447765, 'czterysta czterdzieści siedem tysięcy siedemset sześćdziesiąt pięć'],
		[463931, 'czterysta sześćdziesiąt trzy tysiące dziewięćset trzydzieści jeden'],
		[467619, 'czterysta sześćdziesiąt siedem tysięcy sześćset dziewiętnaście'],
		[474761, 'czterysta siedemdziesiąt cztery tysiące siedemset sześćdziesiąt jeden'],
		[477101, 'czterysta siedemdziesiąt siedem tysięcy sto jeden'],
		[480476, 'czterysta osiemdziesiąt tysięcy czterysta siedemdziesiąt sześć'],
		[480787, 'czterysta osiemdziesiąt tysięcy siedemset osiemdziesiąt siedem'],
		[486612, 'czterysta osiemdziesiąt sześć tysięcy sześćset dwanaście'],
		[487018, 'czterysta osiemdziesiąt siedem tysięcy osiemnaście'],
		[487538, 'czterysta osiemdziesiąt siedem tysięcy pięćset trzydzieści osiem'],
		[491473, 'czterysta dziewięćdziesiąt jeden tysięcy czterysta siedemdziesiąt trzy'],
		[500429, 'pięćset tysięcy czterysta dwadzieścia dziewięć'],
		[501241, 'pięćset jeden tysięcy dwieście czterdzieści jeden'],
		[502172, 'pięćset dwa tysiące sto siedemdziesiąt dwa'],
		[513483, 'pięćset trzynaście tysięcy czterysta osiemdziesiąt trzy'],
		[518113, 'pięćset osiemnaście tysięcy sto trzynaście'],
		[524827, 'pięćset dwadzieścia cztery tysiące osiemset dwadzieścia siedem'],
		[527498, 'pięćset dwadzieścia siedem tysięcy czterysta dziewięćdziesiąt osiem'],
		[545336, 'pięćset czterdzieści pięć tysięcy trzysta trzydzieści sześć'],
		[550365, 'pięćset pięćdziesiąt tysięcy trzysta sześćdziesiąt pięć'],
		[553446, 'pięćset pięćdziesiąt trzy tysiące czterysta czterdzieści sześć'],
		[557514, 'pięćset pięćdziesiąt siedem tysięcy pięćset czternaście'],
		[558855, 'pięćset pięćdziesiąt osiem tysięcy osiemset pięćdziesiąt pięć'],
		[571176, 'pięćset siedemdziesiąt jeden tysięcy sto siedemdziesiąt sześć'],
		[582768, 'pięćset osiemdziesiąt dwa tysiące siedemset sześćdziesiąt osiem'],
		[597807, 'pięćset dziewięćdziesiąt siedem tysięcy osiemset siedem'],
		[608647, 'sześćset osiem tysięcy sześćset czterdzieści siedem'],
		[610965, 'sześćset dziesięć tysięcy dziewięćset sześćdziesiąt pięć'],
		[611849, 'sześćset jedenaście tysięcy osiemset czterdzieści dziewięć'],
		[612380, 'sześćset dwanaście tysięcy trzysta osiemdziesiąt'],
		[655113, 'sześćset pięćdziesiąt pięć tysięcy sto trzynaście'],
		[685425, 'sześćset osiemdziesiąt pięć tysięcy czterysta dwadzieścia pięć'],
		[703684, 'siedemset trzy tysiące sześćset osiemdziesiąt cztery'],
		[712563, 'siedemset dwanaście tysięcy pięćset sześćdziesiąt trzy'],
		[724257, 'siedemset dwadzieścia cztery tysiące dwieście pięćdziesiąt siedem'],
		[726237, 'siedemset dwadzieścia sześć tysięcy dwieście trzydzieści siedem'],
		[772149, 'siedemset siedemdziesiąt dwa tysiące sto czterdzieści dziewięć'],
		[789649, 'siedemset osiemdziesiąt dziewięć tysięcy sześćset czterdzieści dziewięć'],
		[797831, 'siedemset dziewięćdziesiąt siedem tysięcy osiemset trzydzieści jeden'],
		[798055, 'siedemset dziewięćdziesiąt osiem tysięcy pięćdziesiąt pięć'],
		[852900, 'osiemset pięćdziesiąt dwa tysiące dziewięćset'],
		[880150, 'osiemset osiemdziesiąt tysięcy sto pięćdziesiąt'],
		[902317, 'dziewięćset dwa tysiące trzysta siedemnaście'],
		[920887, 'dziewięćset dwadzieścia tysięcy osiemset osiemdziesiąt siedem'],
		[975576, 'dziewięćset siedemdziesiąt pięć tysięcy pięćset siedemdziesiąt sześć'],
		[987982, 'dziewięćset osiemdziesiąt siedem tysięcy dziewięćset osiemdziesiąt dwa'],
		[988147, 'dziewięćset osiemdziesiąt osiem tysięcy sto czterdzieści siedem'],
		[999073, 'dziewięćset dziewięćdziesiąt dziewięć tysięcy siedemdziesiąt trzy'],
		[1020505, 'jeden milion dwadzieścia tysięcy pięćset pięć'],
		[1054036, 'jeden milion pięćdziesiąt cztery tysiące trzydzieści sześć'],
		[1083395, 'jeden milion osiemdziesiąt trzy tysiące trzysta dziewięćdziesiąt pięć'],
		[1107879, 'jeden milion sto siedem tysięcy osiemset siedemdziesiąt dziewięć'],
		[1127642, 'jeden milion sto dwadzieścia siedem tysięcy sześćset czterdzieści dwa'],
		[1128264, 'jeden milion sto dwadzieścia osiem tysięcy dwieście sześćdziesiąt cztery'],
		[1136964, 'jeden milion sto trzydzieści sześć tysięcy dziewięćset sześćdziesiąt cztery'],
		[1165654, 'jeden milion sto sześćdziesiąt pięć tysięcy sześćset pięćdziesiąt cztery'],
		[1176662, 'jeden milion sto siedemdziesiąt sześć tysięcy sześćset sześćdziesiąt dwa'],
		[1216617, 'jeden milion dwieście szesnaście tysięcy sześćset siedemnaście'],
		[
			1224697,
			'jeden milion dwieście dwadzieścia cztery tysiące sześćset dziewięćdziesiąt siedem',
		],
		[1231091, 'jeden milion dwieście trzydzieści jeden tysięcy dziewięćdziesiąt jeden'],
		[1308547, 'jeden milion trzysta osiem tysięcy pięćset czterdzieści siedem'],
		[1330127, 'jeden milion trzysta trzydzieści tysięcy sto dwadzieścia siedem'],
		[1345347, 'jeden milion trzysta czterdzieści pięć tysięcy trzysta czterdzieści siedem'],
		[1356712, 'jeden milion trzysta pięćdziesiąt sześć tysięcy siedemset dwanaście'],
		[1369042, 'jeden milion trzysta sześćdziesiąt dziewięć tysięcy czterdzieści dwa'],
		[
			1397495,
			'jeden milion trzysta dziewięćdziesiąt siedem tysięcy czterysta dziewięćdziesiąt pięć',
		],
		[1402663, 'jeden milion czterysta dwa tysiące sześćset sześćdziesiąt trzy'],
		[1403188, 'jeden milion czterysta trzy tysiące sto osiemdziesiąt osiem'],
		[1430137, 'jeden milion czterysta trzydzieści tysięcy sto trzydzieści siedem'],
		[1433843, 'jeden milion czterysta trzydzieści trzy tysiące osiemset czterdzieści trzy'],
		[1448622, 'jeden milion czterysta czterdzieści osiem tysięcy sześćset dwadzieścia dwa'],
		[1482452, 'jeden milion czterysta osiemdziesiąt dwa tysiące czterysta pięćdziesiąt dwa'],
		[1486782, 'jeden milion czterysta osiemdziesiąt sześć tysięcy siedemset osiemdziesiąt dwa'],
		[
			1486974,
			'jeden milion czterysta osiemdziesiąt sześć tysięcy dziewięćset siedemdziesiąt cztery',
		],
		[1488352, 'jeden milion czterysta osiemdziesiąt osiem tysięcy trzysta pięćdziesiąt dwa'],
		[1490590, 'jeden milion czterysta dziewięćdziesiąt tysięcy pięćset dziewięćdziesiąt'],
		[1541674, 'jeden milion pięćset czterdzieści jeden tysięcy sześćset siedemdziesiąt cztery'],
		[
			1597936,
			'jeden milion pięćset dziewięćdziesiąt siedem tysięcy dziewięćset trzydzieści sześć',
		],
		[1652350, 'jeden milion sześćset pięćdziesiąt dwa tysiące trzysta pięćdziesiąt'],
		[1672821, 'jeden milion sześćset siedemdziesiąt dwa tysiące osiemset dwadzieścia jeden'],
		[1739708, 'jeden milion siedemset trzydzieści dziewięć tysięcy siedemset osiem'],
		[1754100, 'jeden milion siedemset pięćdziesiąt cztery tysiące sto'],
		[1755566, 'jeden milion siedemset pięćdziesiąt pięć tysięcy pięćset sześćdziesiąt sześć'],
		[1810434, 'jeden milion osiemset dziesięć tysięcy czterysta trzydzieści cztery'],
		[1822518, 'jeden milion osiemset dwadzieścia dwa tysiące pięćset osiemnaście'],
		[1940101, 'jeden milion dziewięćset czterdzieści tysięcy sto jeden'],
		[
			1949471,
			'jeden milion dziewięćset czterdzieści dziewięć tysięcy czterysta siedemdziesiąt jeden',
		],
		[2040247, 'dwa miliony czterdzieści tysięcy dwieście czterdzieści siedem'],
		[2058733, 'dwa miliony pięćdziesiąt osiem tysięcy siedemset trzydzieści trzy'],
		[2064350, 'dwa miliony sześćdziesiąt cztery tysiące trzysta pięćdziesiąt'],
		[2097275, 'dwa miliony dziewięćdziesiąt siedem tysięcy dwieście siedemdziesiąt pięć'],
		[2140121, 'dwa miliony sto czterdzieści tysięcy sto dwadzieścia jeden'],
		[2210455, 'dwa miliony dwieście dziesięć tysięcy czterysta pięćdziesiąt pięć'],
		[2225764, 'dwa miliony dwieście dwadzieścia pięć tysięcy siedemset sześćdziesiąt cztery'],
		[2238955, 'dwa miliony dwieście trzydzieści osiem tysięcy dziewięćset pięćdziesiąt pięć'],
		[2360287, 'dwa miliony trzysta sześćdziesiąt tysięcy dwieście osiemdziesiąt siedem'],
		[2365872, 'dwa miliony trzysta sześćdziesiąt pięć tysięcy osiemset siedemdziesiąt dwa'],
		[2366277, 'dwa miliony trzysta sześćdziesiąt sześć tysięcy dwieście siedemdziesiąt siedem'],
		[2367314, 'dwa miliony trzysta sześćdziesiąt siedem tysięcy trzysta czternaście'],
		[2393285, 'dwa miliony trzysta dziewięćdziesiąt trzy tysiące dwieście osiemdziesiąt pięć'],
		[2405928, 'dwa miliony czterysta pięć tysięcy dziewięćset dwadzieścia osiem'],
		[2410279, 'dwa miliony czterysta dziesięć tysięcy dwieście siedemdziesiąt dziewięć'],
		[2411131, 'dwa miliony czterysta jedenaście tysięcy sto trzydzieści jeden'],
		[2426447, 'dwa miliony czterysta dwadzieścia sześć tysięcy czterysta czterdzieści siedem'],
		[2429782, 'dwa miliony czterysta dwadzieścia dziewięć tysięcy siedemset osiemdziesiąt dwa'],
		[2436020, 'dwa miliony czterysta trzydzieści sześć tysięcy dwadzieścia'],
		[
			2445599,
			'dwa miliony czterysta czterdzieści pięć tysięcy pięćset dziewięćdziesiąt dziewięć',
		],
		[
			2468399,
			'dwa miliony czterysta sześćdziesiąt osiem tysięcy trzysta dziewięćdziesiąt dziewięć',
		],
		[2559623, 'dwa miliony pięćset pięćdziesiąt dziewięć tysięcy sześćset dwadzieścia trzy'],
		[2581902, 'dwa miliony pięćset osiemdziesiąt jeden tysięcy dziewięćset dwa'],
		[2585514, 'dwa miliony pięćset osiemdziesiąt pięć tysięcy pięćset czternaście'],
		[2615970, 'dwa miliony sześćset piętnaście tysięcy dziewięćset siedemdziesiąt'],
		[2629360, 'dwa miliony sześćset dwadzieścia dziewięć tysięcy trzysta sześćdziesiąt'],
		[2685708, 'dwa miliony sześćset osiemdziesiąt pięć tysięcy siedemset osiem'],
		[2692163, 'dwa miliony sześćset dziewięćdziesiąt dwa tysiące sto sześćdziesiąt trzy'],
		[2708673, 'dwa miliony siedemset osiem tysięcy sześćset siedemdziesiąt trzy'],
		[
			2771397,
			'dwa miliony siedemset siedemdziesiąt jeden tysięcy trzysta dziewięćdziesiąt siedem',
		],
		[2844309, 'dwa miliony osiemset czterdzieści cztery tysiące trzysta dziewięć'],
		[2902442, 'dwa miliony dziewięćset dwa tysiące czterysta czterdzieści dwa'],
		[2937430, 'dwa miliony dziewięćset trzydzieści siedem tysięcy czterysta trzydzieści'],
		[
			2945966,
			'dwa miliony dziewięćset czterdzieści pięć tysięcy dziewięćset sześćdziesiąt sześć',
		],
		[
			2959451,
			'dwa miliony dziewięćset pięćdziesiąt dziewięć tysięcy czterysta pięćdziesiąt jeden',
		],
		[2993410, 'dwa miliony dziewięćset dziewięćdziesiąt trzy tysiące czterysta dziesięć'],
		[3000285, 'trzy miliony dwieście osiemdziesiąt pięć'],
		[3132638, 'trzy miliony sto trzydzieści dwa tysiące sześćset trzydzieści osiem'],
		[3189381, 'trzy miliony sto osiemdziesiąt dziewięć tysięcy trzysta osiemdziesiąt jeden'],
		[3254872, 'trzy miliony dwieście pięćdziesiąt cztery tysiące osiemset siedemdziesiąt dwa'],
		[3284013, 'trzy miliony dwieście osiemdziesiąt cztery tysiące trzynaście'],
		[
			3293675,
			'trzy miliony dwieście dziewięćdziesiąt trzy tysiące sześćset siedemdziesiąt pięć',
		],
		[3309655, 'trzy miliony trzysta dziewięć tysięcy sześćset pięćdziesiąt pięć'],
		[3347839, 'trzy miliony trzysta czterdzieści siedem tysięcy osiemset trzydzieści dziewięć'],
		[3453089, 'trzy miliony czterysta pięćdziesiąt trzy tysiące osiemdziesiąt dziewięć'],
		[3516313, 'trzy miliony pięćset szesnaście tysięcy trzysta trzynaście'],
		[3544840, 'trzy miliony pięćset czterdzieści cztery tysiące osiemset czterdzieści'],
		[3564189, 'trzy miliony pięćset sześćdziesiąt cztery tysiące sto osiemdziesiąt dziewięć'],
		[3706234, 'trzy miliony siedemset sześć tysięcy dwieście trzydzieści cztery'],
		[3846092, 'trzy miliony osiemset czterdzieści sześć tysięcy dziewięćdziesiąt dwa'],
		[3855658, 'trzy miliony osiemset pięćdziesiąt pięć tysięcy sześćset pięćdziesiąt osiem'],
		[3884017, 'trzy miliony osiemset osiemdziesiąt cztery tysiące siedemnaście'],
		[
			3975772,
			'trzy miliony dziewięćset siedemdziesiąt pięć tysięcy siedemset siedemdziesiąt dwa',
		],
		[
			3999297,
			'trzy miliony dziewięćset dziewięćdziesiąt dziewięć tysięcy dwieście dziewięćdziesiąt siedem',
		],
		[4039911, 'cztery miliony trzydzieści dziewięć tysięcy dziewięćset jedenaście'],
		[4155255, 'cztery miliony sto pięćdziesiąt pięć tysięcy dwieście pięćdziesiąt pięć'],
		[4168733, 'cztery miliony sto sześćdziesiąt osiem tysięcy siedemset trzydzieści trzy'],
		[4214546, 'cztery miliony dwieście czternaście tysięcy pięćset czterdzieści sześć'],
		[4277332, 'cztery miliony dwieście siedemdziesiąt siedem tysięcy trzysta trzydzieści dwa'],
		[
			4488942,
			'cztery miliony czterysta osiemdziesiąt osiem tysięcy dziewięćset czterdzieści dwa',
		],
		[4582136, 'cztery miliony pięćset osiemdziesiąt dwa tysiące sto trzydzieści sześć'],
		[
			4697366,
			'cztery miliony sześćset dziewięćdziesiąt siedem tysięcy trzysta sześćdziesiąt sześć',
		],
		[
			4859788,
			'cztery miliony osiemset pięćdziesiąt dziewięć tysięcy siedemset osiemdziesiąt osiem',
		],
		[
			4944346,
			'cztery miliony dziewięćset czterdzieści cztery tysiące trzysta czterdzieści sześć',
		],
		[5037849, 'pięć milionów trzydzieści siedem tysięcy osiemset czterdzieści dziewięć'],
		[5068582, 'pięć milionów sześćdziesiąt osiem tysięcy pięćset osiemdziesiąt dwa'],
		[5106676, 'pięć milionów sto sześć tysięcy sześćset siedemdziesiąt sześć'],
		[5138558, 'pięć milionów sto trzydzieści osiem tysięcy pięćset pięćdziesiąt osiem'],
		[5184963, 'pięć milionów sto osiemdziesiąt cztery tysiące dziewięćset sześćdziesiąt trzy'],
		[5190711, 'pięć milionów sto dziewięćdziesiąt tysięcy siedemset jedenaście'],
		[5310775, 'pięć milionów trzysta dziesięć tysięcy siedemset siedemdziesiąt pięć'],
		[5408964, 'pięć milionów czterysta osiem tysięcy dziewięćset sześćdziesiąt cztery'],
		[5428458, 'pięć milionów czterysta dwadzieścia osiem tysięcy czterysta pięćdziesiąt osiem'],
		[5437206, 'pięć milionów czterysta trzydzieści siedem tysięcy dwieście sześć'],
		[
			5442729,
			'pięć milionów czterysta czterdzieści dwa tysiące siedemset dwadzieścia dziewięć',
		],
		[5521091, 'pięć milionów pięćset dwadzieścia jeden tysięcy dziewięćdziesiąt jeden'],
		[5780421, 'pięć milionów siedemset osiemdziesiąt tysięcy czterysta dwadzieścia jeden'],
		[
			5933758,
			'pięć milionów dziewięćset trzydzieści trzy tysiące siedemset pięćdziesiąt osiem',
		],
		[
			5982745,
			'pięć milionów dziewięćset osiemdziesiąt dwa tysiące siedemset czterdzieści pięć',
		],
		[6044602, 'sześć milionów czterdzieści cztery tysiące sześćset dwa'],
		[6114716, 'sześć milionów sto czternaście tysięcy siedemset szesnaście'],
		[6118211, 'sześć milionów sto osiemnaście tysięcy dwieście jedenaście'],
		[6287615, 'sześć milionów dwieście osiemdziesiąt siedem tysięcy sześćset piętnaście'],
		[
			6417979,
			'sześć milionów czterysta siedemnaście tysięcy dziewięćset siedemdziesiąt dziewięć',
		],
		[
			6447368,
			'sześć milionów czterysta czterdzieści siedem tysięcy trzysta sześćdziesiąt osiem',
		],
		[
			6672456,
			'sześć milionów sześćset siedemdziesiąt dwa tysiące czterysta pięćdziesiąt sześć',
		],
		[6868301, 'sześć milionów osiemset sześćdziesiąt osiem tysięcy trzysta jeden'],
		[
			6877399,
			'sześć milionów osiemset siedemdziesiąt siedem tysięcy trzysta dziewięćdziesiąt dziewięć',
		],
		[6896612, 'sześć milionów osiemset dziewięćdziesiąt sześć tysięcy sześćset dwanaście'],
		[
			6991474,
			'sześć milionów dziewięćset dziewięćdziesiąt jeden tysięcy czterysta siedemdziesiąt cztery',
		],
		[7072347, 'siedem milionów siedemdziesiąt dwa tysiące trzysta czterdzieści siedem'],
		[7108276, 'siedem milionów sto osiem tysięcy dwieście siedemdziesiąt sześć'],
		[7167740, 'siedem milionów sto sześćdziesiąt siedem tysięcy siedemset czterdzieści'],
		[7308050, 'siedem milionów trzysta osiem tysięcy pięćdziesiąt'],
		[7504409, 'siedem milionów pięćset cztery tysiące czterysta dziewięć'],
		[7621250, 'siedem milionów sześćset dwadzieścia jeden tysięcy dwieście pięćdziesiąt'],
		[
			7769673,
			'siedem milionów siedemset sześćdziesiąt dziewięć tysięcy sześćset siedemdziesiąt trzy',
		],
		[7850729, 'siedem milionów osiemset pięćdziesiąt tysięcy siedemset dwadzieścia dziewięć'],
		[8202987, 'osiem milionów dwieście dwa tysiące dziewięćset osiemdziesiąt siedem'],
		[8326922, 'osiem milionów trzysta dwadzieścia sześć tysięcy dziewięćset dwadzieścia dwa'],
		[
			8486365,
			'osiem milionów czterysta osiemdziesiąt sześć tysięcy trzysta sześćdziesiąt pięć',
		],
		[8494407, 'osiem milionów czterysta dziewięćdziesiąt cztery tysiące czterysta siedem'],
		[
			8546574,
			'osiem milionów pięćset czterdzieści sześć tysięcy pięćset siedemdziesiąt cztery',
		],
		[8623176, 'osiem milionów sześćset dwadzieścia trzy tysiące sto siedemdziesiąt sześć'],
		[8667064, 'osiem milionów sześćset sześćdziesiąt siedem tysięcy sześćdziesiąt cztery'],
		[8713217, 'osiem milionów siedemset trzynaście tysięcy dwieście siedemnaście'],
		[8854405, 'osiem milionów osiemset pięćdziesiąt cztery tysiące czterysta pięć'],
		[
			8871425,
			'osiem milionów osiemset siedemdziesiąt jeden tysięcy czterysta dwadzieścia pięć',
		],
		[8943171, 'osiem milionów dziewięćset czterdzieści trzy tysiące sto siedemdziesiąt jeden'],
		[
			8997841,
			'osiem milionów dziewięćset dziewięćdziesiąt siedem tysięcy osiemset czterdzieści jeden',
		],
		[9012132, 'dziewięć milionów dwanaście tysięcy sto trzydzieści dwa'],
		[9152353, 'dziewięć milionów sto pięćdziesiąt dwa tysiące trzysta pięćdziesiąt trzy'],
		[
			9261424,
			'dziewięć milionów dwieście sześćdziesiąt jeden tysięcy czterysta dwadzieścia cztery',
		],
		[9658270, 'dziewięć milionów sześćset pięćdziesiąt osiem tysięcy dwieście siedemdziesiąt'],
		[
			9946394,
			'dziewięć milionów dziewięćset czterdzieści sześć tysięcy trzysta dziewięćdziesiąt cztery',
		],
		[10100309, 'dziesięć milionów sto tysięcy trzysta dziewięć'],
		[10518197, 'dziesięć milionów pięćset osiemnaście tysięcy sto dziewięćdziesiąt siedem'],
		[10548037, 'dziesięć milionów pięćset czterdzieści osiem tysięcy trzydzieści siedem'],
		[10731125, 'dziesięć milionów siedemset trzydzieści jeden tysięcy sto dwadzieścia pięć'],
		[11079206, 'jedenaście milionów siedemdziesiąt dziewięć tysięcy dwieście sześć'],
		[11316813, 'jedenaście milionów trzysta szesnaście tysięcy osiemset trzynaście'],
		[11424054, 'jedenaście milionów czterysta dwadzieścia cztery tysiące pięćdziesiąt cztery'],
		[11451320, 'jedenaście milionów czterysta pięćdziesiąt jeden tysięcy trzysta dwadzieścia'],
		[11824120, 'jedenaście milionów osiemset dwadzieścia cztery tysiące sto dwadzieścia'],
		[11835613, 'jedenaście milionów osiemset trzydzieści pięć tysięcy sześćset trzynaście'],
		[12017796, 'dwanaście milionów siedemnaście tysięcy siedemset dziewięćdziesiąt sześć'],
		[12230872, 'dwanaście milionów dwieście trzydzieści tysięcy osiemset siedemdziesiąt dwa'],
		[12341115, 'dwanaście milionów trzysta czterdzieści jeden tysięcy sto piętnaście'],
		[12417030, 'dwanaście milionów czterysta siedemnaście tysięcy trzydzieści'],
		[12570030, 'dwanaście milionów pięćset siedemdziesiąt tysięcy trzydzieści'],
		[13113432, 'trzynaście milionów sto trzynaście tysięcy czterysta trzydzieści dwa'],
		[
			13294942,
			'trzynaście milionów dwieście dziewięćdziesiąt cztery tysiące dziewięćset czterdzieści dwa',
		],
		[13400430, 'trzynaście milionów czterysta tysięcy czterysta trzydzieści'],
		[
			13742755,
			'trzynaście milionów siedemset czterdzieści dwa tysiące siedemset pięćdziesiąt pięć',
		],
		[13814708, 'trzynaście milionów osiemset czternaście tysięcy siedemset osiem'],
		[
			14064796,
			'czternaście milionów sześćdziesiąt cztery tysiące siedemset dziewięćdziesiąt sześć',
		],
		[14186008, 'czternaście milionów sto osiemdziesiąt sześć tysięcy osiem'],
		[14281063, 'czternaście milionów dwieście osiemdziesiąt jeden tysięcy sześćdziesiąt trzy'],
		[14332315, 'czternaście milionów trzysta trzydzieści dwa tysiące trzysta piętnaście'],
		[
			14428094,
			'czternaście milionów czterysta dwadzieścia osiem tysięcy dziewięćdziesiąt cztery',
		],
		[14504081, 'czternaście milionów pięćset cztery tysiące osiemdziesiąt jeden'],
		[
			14866651,
			'czternaście milionów osiemset sześćdziesiąt sześć tysięcy sześćset pięćdziesiąt jeden',
		],
		[
			15925771,
			'piętnaście milionów dziewięćset dwadzieścia pięć tysięcy siedemset siedemdziesiąt jeden',
		],
		[
			16342472,
			'szesnaście milionów trzysta czterdzieści dwa tysiące czterysta siedemdziesiąt dwa',
		],
		[
			16376357,
			'szesnaście milionów trzysta siedemdziesiąt sześć tysięcy trzysta pięćdziesiąt siedem',
		],
		[
			16621847,
			'szesnaście milionów sześćset dwadzieścia jeden tysięcy osiemset czterdzieści siedem',
		],
		[
			17661755,
			'siedemnaście milionów sześćset sześćdziesiąt jeden tysięcy siedemset pięćdziesiąt pięć',
		],
		[
			17662632,
			'siedemnaście milionów sześćset sześćdziesiąt dwa tysiące sześćset trzydzieści dwa',
		],
		[
			17786975,
			'siedemnaście milionów siedemset osiemdziesiąt sześć tysięcy dziewięćset siedemdziesiąt pięć',
		],
		[18020180, 'osiemnaście milionów dwadzieścia tysięcy sto osiemdziesiąt'],
		[18078101, 'osiemnaście milionów siedemdziesiąt osiem tysięcy sto jeden'],
		[18405473, 'osiemnaście milionów czterysta pięć tysięcy czterysta siedemdziesiąt trzy'],
		[19123205, 'dziewiętnaście milionów sto dwadzieścia trzy tysiące dwieście pięć'],
		[
			19608894,
			'dziewiętnaście milionów sześćset osiem tysięcy osiemset dziewięćdziesiąt cztery',
		],
		[
			19644491,
			'dziewiętnaście milionów sześćset czterdzieści cztery tysiące czterysta dziewięćdziesiąt jeden',
		],
		[20038941, 'dwadzieścia milionów trzydzieści osiem tysięcy dziewięćset czterdzieści jeden'],
		[20367904, 'dwadzieścia milionów trzysta sześćdziesiąt siedem tysięcy dziewięćset cztery'],
		[
			22365754,
			'dwadzieścia dwa miliony trzysta sześćdziesiąt pięć tysięcy siedemset pięćdziesiąt cztery',
		],
		[22434402, 'dwadzieścia dwa miliony czterysta trzydzieści cztery tysiące czterysta dwa'],
		[22794600, 'dwadzieścia dwa miliony siedemset dziewięćdziesiąt cztery tysiące sześćset'],
		[
			23299587,
			'dwadzieścia trzy miliony dwieście dziewięćdziesiąt dziewięć tysięcy pięćset osiemdziesiąt siedem',
		],
		[23605241, 'dwadzieścia trzy miliony sześćset pięć tysięcy dwieście czterdzieści jeden'],
		[
			24388827,
			'dwadzieścia cztery miliony trzysta osiemdziesiąt osiem tysięcy osiemset dwadzieścia siedem',
		],
		[
			24413894,
			'dwadzieścia cztery miliony czterysta trzynaście tysięcy osiemset dziewięćdziesiąt cztery',
		],
		[
			25294247,
			'dwadzieścia pięć milionów dwieście dziewięćdziesiąt cztery tysiące dwieście czterdzieści siedem',
		],
		[
			25849974,
			'dwadzieścia pięć milionów osiemset czterdzieści dziewięć tysięcy dziewięćset siedemdziesiąt cztery',
		],
		[
			25890255,
			'dwadzieścia pięć milionów osiemset dziewięćdziesiąt tysięcy dwieście pięćdziesiąt pięć',
		],
		[
			26073542,
			'dwadzieścia sześć milionów siedemdziesiąt trzy tysiące pięćset czterdzieści dwa',
		],
		[
			26661492,
			'dwadzieścia sześć milionów sześćset sześćdziesiąt jeden tysięcy czterysta dziewięćdziesiąt dwa',
		],
		[
			26686032,
			'dwadzieścia sześć milionów sześćset osiemdziesiąt sześć tysięcy trzydzieści dwa',
		],
		[
			26691892,
			'dwadzieścia sześć milionów sześćset dziewięćdziesiąt jeden tysięcy osiemset dziewięćdziesiąt dwa',
		],
		[
			26704885,
			'dwadzieścia sześć milionów siedemset cztery tysiące osiemset osiemdziesiąt pięć',
		],
		[27054004, 'dwadzieścia siedem milionów pięćdziesiąt cztery tysiące cztery'],
		[
			27296414,
			'dwadzieścia siedem milionów dwieście dziewięćdziesiąt sześć tysięcy czterysta czternaście',
		],
		[28401660, 'dwadzieścia osiem milionów czterysta jeden tysięcy sześćset sześćdziesiąt'],
		[
			28477974,
			'dwadzieścia osiem milionów czterysta siedemdziesiąt siedem tysięcy dziewięćset siedemdziesiąt cztery',
		],
		[29092803, 'dwadzieścia dziewięć milionów dziewięćdziesiąt dwa tysiące osiemset trzy'],
		[
			29167938,
			'dwadzieścia dziewięć milionów sto sześćdziesiąt siedem tysięcy dziewięćset trzydzieści osiem',
		],
		[
			29435976,
			'dwadzieścia dziewięć milionów czterysta trzydzieści pięć tysięcy dziewięćset siedemdziesiąt sześć',
		],
		[
			29608668,
			'dwadzieścia dziewięć milionów sześćset osiem tysięcy sześćset sześćdziesiąt osiem',
		],
		[
			30069628,
			'trzydzieści milionów sześćdziesiąt dziewięć tysięcy sześćset dwadzieścia osiem',
		],
		[30746014, 'trzydzieści milionów siedemset czterdzieści sześć tysięcy czternaście'],
		[
			30946261,
			'trzydzieści milionów dziewięćset czterdzieści sześć tysięcy dwieście sześćdziesiąt jeden',
		],
		[31326019, 'trzydzieści jeden milionów trzysta dwadzieścia sześć tysięcy dziewiętnaście'],
		[31604086, 'trzydzieści jeden milionów sześćset cztery tysiące osiemdziesiąt sześć'],
		[32037413, 'trzydzieści dwa miliony trzydzieści siedem tysięcy czterysta trzynaście'],
		[
			32881734,
			'trzydzieści dwa miliony osiemset osiemdziesiąt jeden tysięcy siedemset trzydzieści cztery',
		],
		[32900752, 'trzydzieści dwa miliony dziewięćset tysięcy siedemset pięćdziesiąt dwa'],
		[33026813, 'trzydzieści trzy miliony dwadzieścia sześć tysięcy osiemset trzynaście'],
		[
			34579127,
			'trzydzieści cztery miliony pięćset siedemdziesiąt dziewięć tysięcy sto dwadzieścia siedem',
		],
		[
			35521769,
			'trzydzieści pięć milionów pięćset dwadzieścia jeden tysięcy siedemset sześćdziesiąt dziewięć',
		],
		[36041913, 'trzydzieści sześć milionów czterdzieści jeden tysięcy dziewięćset trzynaście'],
		[36614010, 'trzydzieści sześć milionów sześćset czternaście tysięcy dziesięć'],
		[
			36813422,
			'trzydzieści sześć milionów osiemset trzynaście tysięcy czterysta dwadzieścia dwa',
		],
		[
			37114691,
			'trzydzieści siedem milionów sto czternaście tysięcy sześćset dziewięćdziesiąt jeden',
		],
		[
			37199683,
			'trzydzieści siedem milionów sto dziewięćdziesiąt dziewięć tysięcy sześćset osiemdziesiąt trzy',
		],
		[37705615, 'trzydzieści siedem milionów siedemset pięć tysięcy sześćset piętnaście'],
		[
			37884697,
			'trzydzieści siedem milionów osiemset osiemdziesiąt cztery tysiące sześćset dziewięćdziesiąt siedem',
		],
		[
			38460476,
			'trzydzieści osiem milionów czterysta sześćdziesiąt tysięcy czterysta siedemdziesiąt sześć',
		],
		[
			38560748,
			'trzydzieści osiem milionów pięćset sześćdziesiąt tysięcy siedemset czterdzieści osiem',
		],
		[
			38715864,
			'trzydzieści osiem milionów siedemset piętnaście tysięcy osiemset sześćdziesiąt cztery',
		],
		[
			39399408,
			'trzydzieści dziewięć milionów trzysta dziewięćdziesiąt dziewięć tysięcy czterysta osiem',
		],
		[
			40280428,
			'czterdzieści milionów dwieście osiemdziesiąt tysięcy czterysta dwadzieścia osiem',
		],
		[
			40470842,
			'czterdzieści milionów czterysta siedemdziesiąt tysięcy osiemset czterdzieści dwa',
		],
		[41805535, 'czterdzieści jeden milionów osiemset pięć tysięcy pięćset trzydzieści pięć'],
		[
			42725930,
			'czterdzieści dwa miliony siedemset dwadzieścia pięć tysięcy dziewięćset trzydzieści',
		],
		[45632210, 'czterdzieści pięć milionów sześćset trzydzieści dwa tysiące dwieście dziesięć'],
		[
			48147812,
			'czterdzieści osiem milionów sto czterdzieści siedem tysięcy osiemset dwanaście',
		],
		[
			48346523,
			'czterdzieści osiem milionów trzysta czterdzieści sześć tysięcy pięćset dwadzieścia trzy',
		],
		[
			50593086,
			'pięćdziesiąt milionów pięćset dziewięćdziesiąt trzy tysiące osiemdziesiąt sześć',
		],
		[
			50832646,
			'pięćdziesiąt milionów osiemset trzydzieści dwa tysiące sześćset czterdzieści sześć',
		],
		[
			52557351,
			'pięćdziesiąt dwa miliony pięćset pięćdziesiąt siedem tysięcy trzysta pięćdziesiąt jeden',
		],
		[
			54094893,
			'pięćdziesiąt cztery miliony dziewięćdziesiąt cztery tysiące osiemset dziewięćdziesiąt trzy',
		],
		[55045460, 'pięćdziesiąt pięć milionów czterdzieści pięć tysięcy czterysta sześćdziesiąt'],
		[
			56126582,
			'pięćdziesiąt sześć milionów sto dwadzieścia sześć tysięcy pięćset osiemdziesiąt dwa',
		],
		[
			57407559,
			'pięćdziesiąt siedem milionów czterysta siedem tysięcy pięćset pięćdziesiąt dziewięć',
		],
		[
			58285960,
			'pięćdziesiąt osiem milionów dwieście osiemdziesiąt pięć tysięcy dziewięćset sześćdziesiąt',
		],
		[
			59731428,
			'pięćdziesiąt dziewięć milionów siedemset trzydzieści jeden tysięcy czterysta dwadzieścia osiem',
		],
		[
			60568518,
			'sześćdziesiąt milionów pięćset sześćdziesiąt osiem tysięcy pięćset osiemnaście',
		],
		[
			60658450,
			'sześćdziesiąt milionów sześćset pięćdziesiąt osiem tysięcy czterysta pięćdziesiąt',
		],
		[
			62834624,
			'sześćdziesiąt dwa miliony osiemset trzydzieści cztery tysiące sześćset dwadzieścia cztery',
		],
		[63060161, 'sześćdziesiąt trzy miliony sześćdziesiąt tysięcy sto sześćdziesiąt jeden'],
		[
			63511258,
			'sześćdziesiąt trzy miliony pięćset jedenaście tysięcy dwieście pięćdziesiąt osiem',
		],
		[
			63717155,
			'sześćdziesiąt trzy miliony siedemset siedemnaście tysięcy sto pięćdziesiąt pięć',
		],
		[
			63944172,
			'sześćdziesiąt trzy miliony dziewięćset czterdzieści cztery tysiące sto siedemdziesiąt dwa',
		],
		[
			64835252,
			'sześćdziesiąt cztery miliony osiemset trzydzieści pięć tysięcy dwieście pięćdziesiąt dwa',
		],
		[
			67250658,
			'sześćdziesiąt siedem milionów dwieście pięćdziesiąt tysięcy sześćset pięćdziesiąt osiem',
		],
		[
			67405766,
			'sześćdziesiąt siedem milionów czterysta pięć tysięcy siedemset sześćdziesiąt sześć',
		],
		[
			68791927,
			'sześćdziesiąt osiem milionów siedemset dziewięćdziesiąt jeden tysięcy dziewięćset dwadzieścia siedem',
		],
		[69802819, 'sześćdziesiąt dziewięć milionów osiemset dwa tysiące osiemset dziewiętnaście'],
		[
			70099664,
			'siedemdziesiąt milionów dziewięćdziesiąt dziewięć tysięcy sześćset sześćdziesiąt cztery',
		],
		[
			70286088,
			'siedemdziesiąt milionów dwieście osiemdziesiąt sześć tysięcy osiemdziesiąt osiem',
		],
		[
			70289117,
			'siedemdziesiąt milionów dwieście osiemdziesiąt dziewięć tysięcy sto siedemnaście',
		],
		[70317210, 'siedemdziesiąt milionów trzysta siedemnaście tysięcy dwieście dziesięć'],
		[
			71139653,
			'siedemdziesiąt jeden milionów sto trzydzieści dziewięć tysięcy sześćset pięćdziesiąt trzy',
		],
		[
			71985368,
			'siedemdziesiąt jeden milionów dziewięćset osiemdziesiąt pięć tysięcy trzysta sześćdziesiąt osiem',
		],
		[
			72447798,
			'siedemdziesiąt dwa miliony czterysta czterdzieści siedem tysięcy siedemset dziewięćdziesiąt osiem',
		],
		[
			73141454,
			'siedemdziesiąt trzy miliony sto czterdzieści jeden tysięcy czterysta pięćdziesiąt cztery',
		],
		[
			73289251,
			'siedemdziesiąt trzy miliony dwieście osiemdziesiąt dziewięć tysięcy dwieście pięćdziesiąt jeden',
		],
		[
			74219174,
			'siedemdziesiąt cztery miliony dwieście dziewiętnaście tysięcy sto siedemdziesiąt cztery',
		],
		[
			76426167,
			'siedemdziesiąt sześć milionów czterysta dwadzieścia sześć tysięcy sto sześćdziesiąt siedem',
		],
		[
			77872256,
			'siedemdziesiąt siedem milionów osiemset siedemdziesiąt dwa tysiące dwieście pięćdziesiąt sześć',
		],
		[
			78155257,
			'siedemdziesiąt osiem milionów sto pięćdziesiąt pięć tysięcy dwieście pięćdziesiąt siedem',
		],
		[
			79733537,
			'siedemdziesiąt dziewięć milionów siedemset trzydzieści trzy tysiące pięćset trzydzieści siedem',
		],
		[
			80926255,
			'osiemdziesiąt milionów dziewięćset dwadzieścia sześć tysięcy dwieście pięćdziesiąt pięć',
		],
		[
			81514773,
			'osiemdziesiąt jeden milionów pięćset czternaście tysięcy siedemset siedemdziesiąt trzy',
		],
		[82078054, 'osiemdziesiąt dwa miliony siedemdziesiąt osiem tysięcy pięćdziesiąt cztery'],
		[
			82902938,
			'osiemdziesiąt dwa miliony dziewięćset dwa tysiące dziewięćset trzydzieści osiem',
		],
		[
			83729716,
			'osiemdziesiąt trzy miliony siedemset dwadzieścia dziewięć tysięcy siedemset szesnaście',
		],
		[
			86230978,
			'osiemdziesiąt sześć milionów dwieście trzydzieści tysięcy dziewięćset siedemdziesiąt osiem',
		],
		[
			90695435,
			'dziewięćdziesiąt milionów sześćset dziewięćdziesiąt pięć tysięcy czterysta trzydzieści pięć',
		],
		[
			91539772,
			'dziewięćdziesiąt jeden milionów pięćset trzydzieści dziewięć tysięcy siedemset siedemdziesiąt dwa',
		],
		[92509314, 'dziewięćdziesiąt dwa miliony pięćset dziewięć tysięcy trzysta czternaście'],
		[
			94414667,
			'dziewięćdziesiąt cztery miliony czterysta czternaście tysięcy sześćset sześćdziesiąt siedem',
		],
		[
			94701531,
			'dziewięćdziesiąt cztery miliony siedemset jeden tysięcy pięćset trzydzieści jeden',
		],
		[
			95501648,
			'dziewięćdziesiąt pięć milionów pięćset jeden tysięcy sześćset czterdzieści osiem',
		],
		[96096102, 'dziewięćdziesiąt sześć milionów dziewięćdziesiąt sześć tysięcy sto dwa'],
		[96509015, 'dziewięćdziesiąt sześć milionów pięćset dziewięć tysięcy piętnaście'],
		[
			97339792,
			'dziewięćdziesiąt siedem milionów trzysta trzydzieści dziewięć tysięcy siedemset dziewięćdziesiąt dwa',
		],
		[
			97364932,
			'dziewięćdziesiąt siedem milionów trzysta sześćdziesiąt cztery tysiące dziewięćset trzydzieści dwa',
		],
		[
			99574493,
			'dziewięćdziesiąt dziewięć milionów pięćset siedemdziesiąt cztery tysiące czterysta dziewięćdziesiąt trzy',
		],
		[
			99827683,
			'dziewięćdziesiąt dziewięć milionów osiemset dwadzieścia siedem tysięcy sześćset osiemdziesiąt trzy',
		],
	];

	cases.forEach(([input, expected]) => {
		const result = polishSpellingGenerator(input);
		t.is(result, expected);
	});
});

test('it generates decimal fraction if number is not integer', t => {
	const cases = [
		[0.33, 'zero 33/100'],
		[2.45, 'dwa 45/100'],
		[35.12, 'trzydzieści pięć 12/100'],
		[122.45, 'sto dwadzieścia dwa 45/100'],
		[1245.689, 'jeden tysiąc dwieście czterdzieści pięć 69/100'],
	];

	cases.forEach(([input, expected]) => {
		const result = polishSpellingGenerator(input);
		t.is(result, expected);
	});
});

test('it generates minus for negative number', t => {
	const cases = [
		[0, 'zero'],
		[-5, 'minus pięć'],
		[-235, 'minus dwieście trzydzieści pięć'],
		[-3269.75, 'minus trzy tysiące dwieście sześćdziesiąt dziewięć 75/100'],
	];

	cases.forEach(([input, expected]) => {
		const result = polishSpellingGenerator(input);
		t.is(result, expected);
	});
});

test('should throw error for incorrect (NaN) argument provided', t => {
	const cases = [
		['abc', 'Incorrect number provided: abc'],
		['$%!', 'Incorrect number provided: $%!'],
		['1xas13', 'Incorrect number provided: 1xas13'],
		['1234xaf', 'Incorrect number provided: 1234xaf'],
	];

	cases.forEach(([input, errorMessage]) => {
		const error = t.throws(() => polishSpellingGenerator(input));
		t.is(error.message, errorMessage);
	});
});
